BOT_VERSION = "3.0.0"

REGIME_TRENDING_UP   = "TRENDING_UP"
REGIME_TRENDING_DOWN = "TRENDING_DOWN"
REGIME_RANGING       = "RANGING"
REGIME_VOLATILE      = "VOLATILE"
REGIME_NO_TRADE      = "NO_TRADE"

CANDLE_COLS = ["time", "open", "high", "low", "close", "tick_volume", "spread"]

MT5_TIMEFRAMES = {
    "M1":  1,
    "M5":  5,
    "M15": 15,
    "H1":  60,
    "H4":  240,
}

SIGNAL_BUY  = "BUY"
SIGNAL_SELL = "SELL"
SIGNAL_HOLD = "HOLD"

EXIT_SL           = "SL"
EXIT_TP           = "TP"
EXIT_BAR_CLOSE    = "BAR_CLOSE"
EXIT_ADVERSE      = "ADVERSE"
EXIT_EMERGENCY    = "EMERGENCY"

MIN_WIN_RATE_LIVE  = 0.59
TARGET_WIN_RATE    = 0.70
MAX_TRAIN_ITERS    = 20
